consul:
  image: gliderlabs/consul-server
  container_name: consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53:8600/udp"
  net: "dn"
  command: "-bootstrap -ui-dir /ui"
  restart: always

fee-service:
  image: fee-service-external
  ports:
    - "8080"
  net: "dn"
  environment:
    - "SERVICE_NAME=fee-service"
    - "SERVICE_CHECK_HTTP=/health"
    - "SPRING_PROFILES_ACTIVE=consul"
  restart: always

user-service:
  image: user-thrift-service
  ports:
    - "8080"
  net: "dn"
  environment:
    - "SERVICE_NAME=user-service"
    - "SERVICE_CHECK_HTTP=/health"
    - "SPRING_PROFILES_ACTIVE=consul"
  restart: always

payment-service:
  image: payment-service
  ports:
    - "8080"
  net: "dn"
  environment:
    - "SERVICE_NAME=payment-service"
    - "SERVICE_CHECK_HTTP=/health"
    - "SPRING_PROFILES_ACTIVE=consul"
  restart: always

gateway-server:
  image: gateway-server
  container_name: gateway-server
  ports:
    - "9000:9000"
  net: "dn"
  environment:
      - "SERVICE_NAME=gateway-server"
      - "SERVICE_CHECK_HTTP=/health"
      - "SPRING_PROFILES_ACTIVE=consul"
  restart: always